from django.urls import path

from .views import (
    ActivityFeedView,
    DailyOfficerReportView,
    OfficerReportView,
    DailySummaryView,
    WeeklySummaryView,
    DailyOfficerReportXLSXView,
    DailyOfficerReportPDFView,
    WeeklySummaryXLSXView,
    WeeklySummaryPDFView,
)

urlpatterns = [
    path(
        "reports/activity/",
        ActivityFeedView.as_view(),
        name="activity-feed",
    ),
    path(
        "reports/officer/",
        OfficerReportView.as_view(),
        name="officer-report",
    ),
    path(
        "reports/daily/",
        DailyOfficerReportView.as_view(),
        name="daily-officer-report",
    ),
        path(
        "reports/daily/summary/",
        DailySummaryView.as_view(),
        name="daily-summary",
    ),
    path(
    "reports/weekly/",
    WeeklySummaryView.as_view(),
    name="weekly-summary",
    ),
    path(
    "reports/daily/export/xlsx/",
    DailyOfficerReportXLSXView.as_view(),
    name="daily-officer-report-xlsx",
    ),
    path(
    "reports/daily/export/pdf/",
    DailyOfficerReportPDFView.as_view(),
    name="daily-officer-report-pdf",
    ),
    path(
        "reports/weekly/export/xlsx/",
        WeeklySummaryXLSXView.as_view(),
        name="weekly-summary-xlsx",
    ),
    path(
        "reports/weekly/export/pdf/",
        WeeklySummaryPDFView.as_view(),
        name="weekly-summary-pdf",
    ),
]