# Generated by Django 5.2.17 on 2026-09-03 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0002_shift_distance_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, help_text='Percentage, 0-100. A dying battery explains a trail that stops.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panic_events', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panic_events_resolved', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panic_events', to='shifts.shift')),
            ],
            options={
                'db_table': 'alerts_panicevent',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['officer', 'triggered_at'], name='alerts_pani_officer_83fa9d_idx'), models.Index(fields=['status'], name='alerts_pani_status_245087_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('officer',), name='unique_active_panic_per_officer'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_at__isnull', False), _connector='OR'), name='cancelled_panic_has_a_cancelled_at'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'resolved'), _negated=True), models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False)), _connector='OR'), name='resolved_panic_has_a_resolver')],
            },
        ),
    ]
