# Generated by Django 6.0.7 on 2026-08-29 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=8)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shifts_shift',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(help_text='When the phone captured it.')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When the server stored it.')),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('network_type', models.CharField(choices=[('wifi', 'Wi-Fi'), ('mobile', 'Mobile data'), ('none', 'No connection'), ('unknown', 'Unknown')], default='unknown', max_length=8)),
                ('is_offline_sync', models.BooleanField(default=False)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='shifts.shift')),
            ],
            options={
                'db_table': 'shifts_locationping',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status', 'started_at'], name='shifts_shif_status_b71611_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('officer',), name='unique_active_shift_per_officer'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='shift_ends_after_it_starts'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['shift', 'recorded_at'], name='shifts_loca_shift_i_5c8a47_idx'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['officer', 'recorded_at'], name='shifts_loca_officer_a6022c_idx'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['recorded_at'], name='shifts_loca_recorde_23f13b_idx'),
        ),
    ]
