# Generated by Django 5.2.17 on 2026-09-02 20:02

import math

from django.db import migrations, models

# Duplicated from shifts/services.py on purpose. A migration must keep
# replaying correctly from an empty database forever, so it cannot depend on
# live application code that may be renamed or rewritten later, and
# apps.get_model() returns the historical model, not the real Shift/
# LocationPing classes shift_distance_m was written against. This copy is
# frozen at this point in history — a later change to services.py must not
# alter what an already-applied migration did.

EARTH_RADIUS_M = 6_371_000
MIN_SEGMENT_M = 10.0
MAX_ACCURACY_M = 100.0


def _haversine_m(lat1, lon1, lat2, lon2):
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * EARTH_RADIUS_M * math.asin(math.sqrt(a))


def _shift_distance_m(pings):
    total = 0.0
    previous = None
    for ping in pings:
        if ping.accuracy_m is not None and ping.accuracy_m > MAX_ACCURACY_M:
            continue
        if previous is not None:
            segment = _haversine_m(
                float(previous.latitude),
                float(previous.longitude),
                float(ping.latitude),
                float(ping.longitude),
            )
            if segment >= MIN_SEGMENT_M:
                total += segment
                previous = ping
        else:
            previous = ping
    return int(total)


def backfill_distance_m(apps, schema_editor):
    Shift = apps.get_model("shifts", "Shift")
    LocationPing = apps.get_model("shifts", "LocationPing")
    for shift in Shift.objects.all():
        pings = LocationPing.objects.filter(shift=shift).order_by("recorded_at")
        shift.distance_m = _shift_distance_m(pings)
        shift.save(update_fields=["distance_m"])


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='distance_m',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_distance_m, reverse_code=migrations.RunPython.noop),
    ]
