# Generated by Django 5.2.17 on 2026-09-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift_distance_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='ended_automatically',
            field=models.BooleanField(default=False),
        ),
    ]
