# Generated by Django 5.2.17 on 2026-08-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='accounts_de_user_id_d068f5_idx',
            old_name='users_devic_user_id_92ecdc_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='accounts_pa_user_id_ba1dfe_idx',
            old_name='users_passw_user_id_350413_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_role_2b136f_idx',
            old_name='users_user_role_e1ec1a_idx',
        ),
        migrations.AlterModelTable(
            name='devicetoken',
            table='accounts_devicetoken',
        ),
        migrations.AlterModelTable(
            name='passwordresetcode',
            table='accounts_passwordresetcode',
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
    ]
