# Generated by Django 6.0.7 on 2026-08-30 16:04

import django.db.models.deletion
import missions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=16)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('started_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('started_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('completed_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('completed_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('ack_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'missions_mission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('acknowledged', 'Acknowledged'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('photo_added', 'Photo added'), ('note_added', 'Note added'), ('ack_alert_sent', 'Acknowledgement alert sent')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_events', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='missions.mission')),
            ],
            options={
                'db_table': 'missions_missionevent',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(unique=True)),
                ('image', models.FileField(upload_to=missions.models.mission_photo_path)),
                ('captured_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='missions.mission')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'missions_missionphoto',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['status', '-created_at'], name='missions_mi_status_1a88e7_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['assigned_to', 'status'], name='missions_mi_assigne_3f2f15_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['priority', 'status'], name='missions_mi_priorit_b3e3cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancellation_reason', ''), _negated=True), _connector='OR'), name='cancelled_mission_has_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'cancelled']), ('assigned_to__isnull', False), _connector='OR'), name='active_mission_has_an_assignee'),
        ),
        migrations.AddIndex(
            model_name='missionevent',
            index=models.Index(fields=['mission', 'created_at'], name='missions_mi_mission_dd51b0_idx'),
        ),
        migrations.AddIndex(
            model_name='missionphoto',
            index=models.Index(fields=['mission', 'uploaded_at'], name='missions_mi_mission_c4eb5d_idx'),
        ),
    ]
