# Generated by Django 6.0.7 on 2026-09-15 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='assigned_officers',
            field=models.ManyToManyField(blank=True, related_name='missions_assigned_new', to=settings.AUTH_USER_MODEL),
        ),
    ]
