# Generated by Django 5.2.17 on 2026-09-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_copy_assignees'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mission',
            name='active_mission_has_an_assignee',
        ),
        migrations.RemoveIndex(
            model_name='mission',
            name='missions_mi_assigne_3f2f15_idx',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='assigned_to',
        ),
    ]
