# Generated by Django 5.2.17 on 2026-09-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_remove_old_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='assigned_officers',
            new_name='assigned_to',
        ),
    ]
