# Generated by Django 5.2.17 on 2026-09-15 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_rename_assigned_officers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='missions_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
