# Generated by Django 5.2.17 on 2026-09-15 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_assigned_to_related_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='category',
            field=models.CharField(choices=[('Municipal', 'Municipal'), ('Sanitation', 'Sanitation'), ('Traffic', 'Traffic'), ('Infrastructure', 'Infrastructure')], default='Municipal', max_length=20),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['category', 'status'], name='missions_mi_categor_e6f718_idx'),
        ),
    ]
