# Generated by Django 6.0.7 on 2026-09-16 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_mission_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_periods', to='missions.mission')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_work_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'missions_missionwork',
                'ordering': ['started_at'],
                'indexes': [models.Index(fields=['mission', 'ended_at'], name='missions_mi_mission_854bdb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('officer',), name='one_open_mission_work_per_officer'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='mission_work_ends_after_it_starts')],
            },
        ),
    ]
