# Generated by Django 6.0.7 on 2026-09-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_mission_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='worked_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='missionevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('acknowledged', 'Acknowledged'), ('started', 'Started'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('photo_added', 'Photo added'), ('note_added', 'Note added'), ('ack_alert_sent', 'Acknowledgement alert sent')], max_length=16),
        ),
    ]
